### ISSUE TITLE
500 Internal Server error på serveren

### ISSUE THREAD

**Issue by cenh** [cenh/ProjectStockSD#42]
Nogle gange får man en 500 eller 403 status kode, når man navigerer rundt på serveren. Det ser ud til at kunne reproduceres ofte, hvis man f.eks. bliver ved med at refreshe.

Kan være serveren der bugger grundet hukommelse eller for mange requests.

**Comment by ninjalf2** [comment]
Fik bare 500 under /projects/. Det gik i sig selv da jeg genstartede httpd or mariadb. Sikkert mangel på hukkommelse.

**Comment by ninjalf2** [comment]
/projects/9 giver ingen problemer, men /projects/14 giver 500. Måske ikke mangel på hukkommelse alligevel.

**Comment by cenh** [comment]
Det virker ret tilfældigt på nuværende tidspunkt, specielt fordi den også nogen gange skriver 403 permission denied (Eller hvad 403 nu er).

**Comment by cenh** [comment]
Fejl skyldes at serveren udelukker/banner folk som spammer requests til den.
